# Generated by Django 3.2.6 on 2021-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Contact Number'),
        ),
    ]
